### ISSUE TITLE
Fumble Recovery Touchdowns Not Calculated in Fantasy Production?

### ISSUE THREAD

**Issue by marvin3FF** [nflverse/nflfastR#401] opened 2022-12-09 15:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Have you installed the latest development version of the package(s) in question?

- [X] I have installed the latest development version of the package.

### What version of the package do you have?

nflfastR (4.5.0.9001)

### Describe the bug

I was digging into Treylon Burks' production this year. When I ran **calculate_player_stats", I noticed** that his Week 12 production does not include his fumble recovery touchdown after Derrick Henry lost the ball.

I'm not sure if it's standard to exclude that touchdown, but most of the sites I looked into included this touchdown as a part of his Week 12 score.

Speaking with Tan, he suggested I submit a ticket.

### Reprex

```r
pbp <- load_pbp(2022:2022)

pbp_mod <- pbp %>%
  filter(rush_attempt == 1 | pass_attempt == 1) %>%
  filter(!is.na(epa))%>%
  filter(season_type == "REG")

weekly <- calculate_player_stats(pbp_mod, weekly = TRUE)%>%
  
weekly_Burks <- weekly %>%
  filter(player_id == "00-0037742")
```

### Expected Behavior

I expected Burks' Week 12 production to include the touchdown.

### nflverse_sitrep

```r
-- System Info --------------------------------------------------------------------------------------------------------------------------------------------------
* R version 4.1.2 (2021-11-01)   * Running under: Windows 10 x64 (build 22000)
-- nflverse Packages --------------------------------------------------------------------------------------------------------------------------------------------
* nflreadr (1.3.1.05)    * nflseedR (1.1.0.9001)  * nflplotR (1.1.0.9001)  
* nflfastR (4.5.0.9001)  * nfl4th   (1.0.2.9004)  * nflverse (1.0.2)       
-- nflverse Options ---------------------------------------------------------------------------------------------------------------------------------------------
No options set for nflreadr, nflfastR, nflseedR, nfl4th, nflplotR, and nflverse
-- nflverse Dependencies ----------------------------------------------------------------------------------------------------------------------------------------
* askpass     (1.1)     * gtable      (0.3.1)    * progressr    (0.11.0)   
* bit         (4.0.4)   * hms         (1.1.2)    * proto        (1.0.0)    
* bit64       (4.0.5)   * httr        (1.4.4)    * purrr        (0.3.4)    
* cachem      (1.0.6)   * isoband     (0.2.5)    * R6           (2.5.1)    
* cli         (3.3.0)   * janitor     (2.1.0)    * rappdirs     (0.3.3)    
* clipr       (0.8.0)   * jsonlite    (1.8.0)    * RColorBrewer (1.1-3)    
* codetools   (0.2-18)  * labeling    (0.4.2)    * Rcpp         (1.0.9)    
* colorspace  (2.0-3)   * lattice     (0.20-45)  * readr        (2.1.2)    
* cpp11       (0.4.2)   * lifecycle   (1.0.1)    * rlang        (1.0.5)    
* crayon      (1.5.1)   * listenv     (0.8.0)    * rstudioapi   (0.14)     
* curl        (4.3.2)   * lubridate   (1.8.0)    * scales       (1.2.1)    
* data.table  (1.14.2)  * magick      (2.7.3)    * snakecase    (0.11.0)   
* digest      (0.6.29)  * magrittr    (2.0.3)    * stringi      (1.7.8)    
* dplyr       (1.0.10)  * MASS        (7.3-54)   * stringr      (1.4.1)    
* ellipsis    (0.3.2)   * Matrix      (1.3-4)    * sys          (3.4)      
* fansi       (1.0.3)   * memoise     (2.0.1)    * tibble       (3.1.8)    
* farver      (2.1.1)   * mgcv        (1.8-38)   * tidyr        (1.2.0)    
* fastmap     (1.1.0)   * mime        (0.12)     * tidyselect   (1.1.2)    
* fastrmodels (1.0.2)   * munsell     (0.5.0)    * timechange   (0.1.1)    
* furrr       (0.3.1)   * nlme        (3.1-153)  * tzdb         (0.3.0)    
* future      (1.28.0)  * openssl     (2.0.2)    * utf8         (1.2.2)    
* generics    (0.1.3)   * parallelly  (1.32.1)   * vctrs        (0.4.1)    
* ggplot2     (3.3.6)   * pillar      (1.8.1)    * viridisLite  (0.4.1)    
* globals     (0.16.1)  * pkgconfig   (2.0.3)    * vroom        (1.5.7)    
* glue        (1.6.2)   * prettyunits (1.1.1)    * withr        (2.5.0)    
* gsubfn      (0.7)     * progress    (1.2.2)    * xgboost      (1.6.0.1)
```

**Comment by guga31bb** [comment] 2022-12-09 18:08
Duplicate of #336

**Closed by guga31bb** 2022-12-09 18:08 UTC

**Comment by marvin3FF** [comment] 2022-12-18 15:22
@guga31bb thanks for marking as a duplicate, I did not catch that one. Do you know if there are plans to add this soon as part of the fantasy production? With Tyreek Hill scoring last week on a fumble recovery as well, we now have a couple of instances where this makes a difference. Maybe more, but those are the two that to come to mind since they're mostly fantasy relevant
