### ISSUE TITLE
receiver_player_name/id mislabelled in 2005-07 season pbp data 

### ISSUE THREAD

**Issue by RicShern** [nflverse/nflfastR#308] opened 2021-12-15 23:46 UTC
It appears there might be a issue that targeted receiver is labeled NA when the pass is incomplete in 2005-2007 season pbp database. Not sure if other seasons or every receivers have a similar issue.
![D03FF7B5-5B93-4392-8620-4C979086540C](https://user-images.githubusercontent.com/76773701/146282328-529f3787-e69a-4640-9927-f6e97bf07c34.png)

**Comment by mrcaseb** [comment] 2022-01-27 16:09
There is definitely something going on with intended receivers in 2005 - 2008

```r
pbp_db |> 
  filter(is.na(receiver_player_name), complete_pass == 0, !is.na(name), pass_attempt == 1) |> 
  count(season, receiver_player_name) |> 
  collect() |> 
  ggplot(aes(x = season, y = n)) +
  geom_col(width = 0.5)

```

![grafik](https://user-images.githubusercontent.com/38586519/151397282-cf1ed9dd-7fd8-4809-88c6-a1d62e9cac66.png)

**Comment by guga31bb** [comment] 2022-01-27 17:11
Duplicate of https://github.com/nflverse/nflfastR/issues/2 / NFL data issue

**Closed by guga31bb** 2022-01-27 17:11 UTC
